stages:
  - build
  - test
  - release

variables:
  GIT_DEPTH: "3"
  SAST_TARGET: request_session
  SONARQUBE_TARGET: request_session,test
  PYLINT_TARGET: request_session test
  PYTEST_COVERAGE_TARGET: request_session

mypy:
  stage: build
  image: kiwicom/mypy:0.620
  script:
    - mypy -p request_session --ignore-missing-imports

include:
  - "https://ci-files.skypicker.com/templates/build/pre_commit.yml"
  - "https://ci-files.skypicker.com/templates/build/zoo.yml"
  - "https://ci-files.skypicker.com/templates/build/tox_init.yml"
  - "https://ci-files.skypicker.com/templates/test/tox_tests.yml"
  - "https://ci-files.skypicker.com/templates/test/dependency_scanning.yml"
  - "https://ci-files.skypicker.com/templates/test/license_management.yml"
  - "https://ci-files.skypicker.com/templates/test/sast.yml"
  - "https://ci-files.skypicker.com/templates/release/sonarqube_scan.yml"
  - "https://ci-files.skypicker.com/templates/release/sonarqube_preview.yml"
